name: QuickChat-backend

on:
  push:
    branches:
      - main 

jobs:
  QuickChat-backend:
    name: Testing and Building app
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DB_HOST: localhost
      DB_DIALECT: postgres
      JSON_WEB_SECRET: 'quick_chat_secret'
      DATABASE_URL: postgresql://postgres.bnmgjmxrqvqupbvkqcdw:QuickChat@testDb@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      SUPABASE_URL: "https://evgvsjlaibgfnjizjzyi.supabase.co"
      SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Z3ZzamxhaWJnZm5qaXpqenlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTIzOTEsImV4cCI6MjA2NDA4ODM5MX0.14BAK2LXLfXLbZDp1RnWfgzUQJKVHQdG79f-KsN4cOU'
      SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Z3ZzamxhaWJnZm5qaXpqenlpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODUxMjM5MSwiZXhwIjoyMDY0MDg4MzkxfQ.RgLASpMIr5C1aSuiV19cm4HYVH63gknrprxBanEn8fs"
      BUCKET_NAME: "quick-chat"
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      EMAIL: 'quickChat.verify@gmail.com'
      PASSWORD: 'wywb pyvn daaq hjyc'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx eslint .
        
      - name: Test the app
        run: npm test

      - name: Install Typescript
        run: npm install -g typescript
        
      - name: Build app
        run : tsc

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."          
          target: ${{ secrets.EC2_APP_PATH }}
      - name: Restart app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_APP_PATH }}
            npm install
            pm2 restart quickchat-backend || pm2 start dist/server.js --name quickchat-backend